### ISSUE TITLE
파일 분리 및 리팩토링

### ISSUE THREAD

**Issue by khk811** [cub42d/cub3d#12]
주석 작성 중에 몇몇 함수는 너무 길고, 함수 이름이나 변수 이름, 구조가 직관적이지 않은 부분이 있어 수정을 하고 싶습니다. 현재까지 작성한 주석은 push하고 코드를 정리해도 될까요?

**Comment by 42hm** [comment]
넵 좋습니다🤗🤗 push 하시면 파일 변경사항 확인해보겠습니다!
