### ISSUE TITLE
벽의 동서남북 텍스쳐 설정 문제

### ISSUE THREAD

**Issue by khk811** [cub42d/cub3d#13]
튜토리얼을 그대로 따라하다보니 현재 저희 cub3D에서 플레이어의 theta값 (초기 시점 방향각)이 0일때 서쪽을 바라보는 상황이 되었습니다.
그래서 '0도면 왠지 북쪽을 바라봐야 할것 같은데' 라는 생각이 들어 이슈에 올립니다.
<img width="432" alt="Screen Shot 2022-07-28 at 1 30 18 PM" src="https://user-images.githubusercontent.com/26704946/181420779-6a2f0922-6eba-4823-8e67-d1f2d659fbb9.png">
현재 main.c의 170~180번째 줄 (get_wall_intersection 함수의 wall_dir 결정 부분)에서 x, y의 증가에 따라 벽의 방향을 결정하는 부분이 있습니다.

<img width="712" alt="Screen Shot 2022-07-28 at 1 29 16 PM" src="https://user-images.githubusercontent.com/26704946/181420679-ee533a9c-8f6e-42ed-869a-a2c1c96cc3c6.png">
위 이미지와 같이 튜토리얼에서는 맵의 x,y와 스크린의 x,y를 약간 다르게 처리해서 그런지 현재 코드의 방향을 결정하는 부분이 이해가 잘 안가는 상황입니다. 이 부분이 왜 이런지, 어떻게 해결하면 좋을지 코멘트 남겨주시면 감사합니다.

**Comment by 42hm** [comment]
음... map 파일에서 어차피 ESWN으로 표기가 되기 때문에 물론 0도가 N 이면 좋겠지만 상관 없을 듯 합니다!
