### ISSUE TITLE
마우스에 의한 시점 변환 개선

### ISSUE THREAD

**Issue by khk811** [cub42d/cub3d#15]
화면의 좌우 20%에 마우스가 존재했을때만 그쪽 방향으로 회전을 했었는데, mlx_hook의 mouse move 이벤트를 받아서 마우스의 움직임 - 이전 마우스 좌표와 현재 좌표의 거리에 비례해서 플레이어의 시점을 회전하게 개선했습니다.

**Comment by 42hm** [comment]
너무너무 좋습니당!!!!!!
