### ISSUE TITLE
[review requests] merge에 성공했습니다

### ISSUE THREAD

**Issue by 42hm** [cub42d/cub3d#17]
## Description

감격스러운 아침입니다😂
이식수술이 이렇게 재밌을줄이야...!!!
현낌님 raycast 하시느라 너무너무 고생 많으셨어요!
마스터 브랜치 깃클론하셔서 한번 쭉 훑어보시고 리뷰남겨주세요!

## Progress

- [ ] 현낌님의 의도에 맞게 이식수술이 성공됐나요?
- [ ] 현낌님의 코드가 잘 들어가 있나요?
- [ ] 특이사항이 있을까요? 실험부탁드립니다 :)

## ETC

노미도.... 다 맞췄답니다 크캬캬캬캬캬

**Comment by khk811** [comment]
mouse_move_event에 정적변수로 선언해둔 int x, int y가 있었는데 일반 int로 변경한것을 확인했습니다.
그래서 제 개인 맥북에서 잘 작동하는지 보니까, 마우스 움직임에 딜레이?가 약간 있고 너무 많이 회전하는것 같아서 현재 클러스터 맥에서 실행해봤습니다. 실행결과 클러스터 맥에서 해당 코드가 정말로 지나치게 회전을 많이 해서 해당 부분의 코드를 수정해야 할것 같습니다.
정적변수를 일반변수로 바꾸신 특별한 이유가 있다면 알려주시면 정말 감사합니다.

**Comment by khk811** [comment]
그리고 mandatory와 bonus의 내용 분리도 해야 할것 같습니다 (으아아앙)

**Comment by 42hm** [comment]
움 static 을 일반으로 바꾼게 아마도..... 잠결에 바꾼 것 같아요! 특별한 이유는 없었던것.....같...은... 보너스ㅠㅠㅠㅠㅠ폴더 음..... 분리 해야하는게 맞겠죠 ㅠㅠ?

**Comment by 42hm** [comment]
수정하실 부분 마스터에 push 하셔도 돼요!!!

**Comment by khk811** [comment]
일단 mouse_move_event를 원래 함수처럼 static int를 써서 수정하였습니다. 근데 마우스 이벤트는 보너스에 해당되니까 별도의 폴더에 넣어서 관리를 해야할것 같은데 src_bonus라고 폴더를 만들어서 관리를 하는 편이 좋을까요? 만약 별도의 보너스 폴더를 만들어서 관리를 한다고 한다면 src_bonus 폴더를 만들기와 거기에 따른 메이크파일 룰 수정을 부탁드려도 될까요?

**Comment by 42hm** [comment]
그러면 mandatory와 bonus의 소스 및 기능은 같지만 소스 자체는 별도의 bonus 폴더로 만들어 make bonus룰을 만드는건 어떨까요?!

**Comment by khk811** [comment]
네! 그렇게 해주신다면 정말 감사합니다! 근데 그렇다면 그냥 지금 상태에서는 src안에 전부 구현하고 나중에 폴더랑 룰을 만드는게 좋을거 같네요

**Comment by 42hm** [comment]
7월 31일 AM 10:17 push [feat : refactoring code, fix player default theta]


vu.h header를 삭제하고 cub3d.h header로 몰았습니다.
클러스터에서 마우스의 로테이션 속도가 빠른것 같아 ROT_UNIT을 0.02로 낮추었습니다.
맵이 작을 때 sx 1080 sy 1000에서 texture render 오류가 일어나 1280 960으로 바꾸었습니다.
또, 동서남북 정확한 theta 값을 적용시켰으며, player 첫 위치가 약간 어긋나 0.5 씩 더해주니 딱 맞게 됐습니당!
그리고.... 뭐했지... maps/test0.cub 을 실행시키면 확인이 가능하십니다!
