### ISSUE TITLE
[Study] 튜토리얼 코드 주석 추가 및 이해

### ISSUE THREAD

**Issue by 42hm** [cub42d/cub3d#2]
## Description

레이케스팅 튜토리얼 끝내고 이해

## Progress

- [x] 예시 코드에 주석 붙이기
- [x] 기본적인 레이캐스팅 이해

**Comment by 42hm** [comment]
스트레스 받지 마세요 (__)

**Comment by khk811** [comment]
위 progress 리스트에 내용추가를 해도 될까요?

**Comment by 42hm** [comment]
넵! 추가하셔도 됩니당! 편집으로요!!
