### ISSUE TITLE
[bug] 맵 파싱 Null terminated 보장

### ISSUE THREAD

**Issue by codeyoma** [cub42d/cub3d#6]
## Description

* 맵 파싱 단계에서 (parser_map 파일) 맵이 `딱 크기가 2일 때`, 널로 끝나지 않을 수 있을 것 같은 생각이 문득 갑자기 머리를 스쳐지나가는 느낌이 듭니다.

## Progress
- [x] NULL 터미네이팅 보장하기

**Comment by 42hm** [comment]
2로 끝나는걸 넣지 맙시다...
