### ISSUE TITLE
[To do] Raycasting Tutorial for Cub3D by 'joongbin'

### ISSUE THREAD

**Issue by khk811** [cub42d/cub3d#7]
## Description

https://www.notion.so/1-133e9a36f2a3437a8becf6f90a2f2da3
강중빈 멘토님이 작성해주신 레이캐스팅 튜토리얼의 진행 - 구현 상황 및 남은 task 기록.

## Progress

- [x] The world : fov 이해
- [x] The wall : ray - 벽 판정 부분
- [x] The height : player 거리에 따른 벽 높이 결정
- [x] The player : player 회전 및 이동
- [x] The texture : 벽에 texture 입히기 및 광원처리
- [x] The floor : 천장, 바닥 처리

**Comment by 42hm** [comment]
스프라이트 처리는 보너스와 함께 해보겠습니다 :)

**Comment by khk811** [comment]
그러면 튜토리얼의 마지막 the sprite는 bonus 이슈에 넣겠습니다. sprite 제외하고 튜토리얼의 모든 항목을 구현했기 때문에 이 이슈는 닫을께요!
