### ISSUE TITLE
[To do - Subtask] Tuto : The texture - texture by direction, luminosity etc.

### ISSUE THREAD

**Issue by khk811** [cub42d/cub3d#8]
## Description

강중빈 멘토님 튜토리얼 내 '텍스쳐 입히기'의 하위 작업들 입니다.

## Progress

- [x] 동, 서, 남, 북에 따른 각각 다른 텍스쳐 로딩

## ETC

현재 ray_casting_test 브랜치 내에 작성한 코드는 벽돌 텍스쳐만 사용합니다.
그 텍스쳐를 위해 mlx 픽셀에 관련된 변수(bit per pixle, line_len, endian)를 선언해 주었는데, 각각의 텍스쳐 마다 변수를 주어야 한다면 비효율적일것 같아서 아예 텍스쳐만 저장할 배열을 생성하고 받은 이미지를 제거(mlx_image_destory)하는게 낫다는 같다는 생각이 들었습니다.

**Comment by khk811** [comment]
extra로 올려놓은 광원처리는 삭제하겠습니다. (방향에 따른 비트맵 파일 처리는 리팩토링에 해당되기 때문에 다른 이슈로 옮기겠습니다.) 이 이슈도 닫겠습니다!

**Comment by 42hm** [comment]
제가 이따 이슈 또 올리겠습니당! 점심 맛있게 드셔요!
